# version: '3.8'

# services:
#   nginx:
#     image: nginx:alpine
#     container_name: nginx
#     restart: unless-stopped
#     ports:
#       - "${HOST_HTTP_PORT:-80}:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     networks:
#       - web

# networks:
#   web:
#     name: ${DOCKER_NETWORK:-devsopserver_net}
#     external: true


services:
  nextjs:
    image: my-nextjs-app:latest
    container_name: nextjs
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
    networks:
      - web

networks:
  web:
    name: devopsserver_net
    driver: bridge