name: Deploy Next.js to Kali
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Stop Old Container
        run: docker stop my-nextjs-app || true && docker rm my-nextjs-app || true
      - name: Build Docker Image
        run: docker build -t my-nextjs-app:latest .
      - name: Run New Container
        run: docker run -d --name nextjs-app -p 8081:3000 nextjs-app   